### ISSUE TITLE
Adding a body or footer causes a panic

### ISSUE THREAD

**Issue by pepperoni505** [zakarumych/egui-snarl#27]
Adding the following functions to `DemoViewer` in the sample results in the program panicking: `assertion failed: max_rect.is_finite()` from `egui-0.28.1\src\layout.rs:420:9`
```rs
fn has_footer(&mut self, node: &DemoNode) -> bool {
    true
}

fn show_footer(
    &mut self,
    node: NodeId,
    inputs: &[InPin],
    outputs: &[OutPin],
    ui: &mut Ui,
    scale: f32,
    snarl: &mut Snarl<DemoNode>,
) {
    ui.button("test");
}
```

The issue stems from these lines which pass infinity as a parameter to the rect allocation: https://github.com/zakarumych/egui-snarl/blob/b61a98041ad67ab2e9eaabf8cf72352efab81d86/src/ui.rs#L1391-L1392 https://github.com/zakarumych/egui-snarl/blob/b61a98041ad67ab2e9eaabf8cf72352efab81d86/src/ui.rs#L1131-L1134

A suitable (untested!) solution could be to change `f32::INFINITY` to `f32::MAX`

**Comment by zakarumych** [comment]
Fixed in 9aec7c0f395b69823c0d46bf0bba6721cf224386
