### ISSUE TITLE
Web demo freaks out (keeps zooming)

### ISSUE THREAD

**Issue by SpaceMacGyver** [zakarumych/egui-snarl#28]
Not sure how much of this is my own environment; sitting on kubuntu 24.04 and have tried both Firefox (128.0.3) and Chromium (127.0.6533.88).  Basically, as soon as I hit the web demo page, it starts zooming in (or perhaps scaling) and rapidly becomes unusable.

**Comment by zakarumych** [comment]
Thank you for pointing to this issue.
It was related to how eframe operate in wasm environment.
For some reason if canvas size is not set it keeps making it bigger and bigger

**Comment by zakarumych** [comment]
Fixed in [003705c](https://github.com/zakarumych/egui-snarl/commit/003705c6cfa3cbba768bfc261960e9e7415d7def)
