### ISSUE TITLE
How to get the currently selected node?

### ISSUE THREAD

**Issue by Capytara** [zakarumych/egui-snarl#31]
Thank you for your excellent work, it has helped me a lot !
But I have a problem now. I want to implement a function similar to inspector. When the user clicks a node, an inspector will pop up. But I don't seem to have found an function to get the currently clicked node.

**Comment by DanielAdolfsson** [comment]
Yes this feels like this is a missing feature.

**Comment by zakarumych** [comment]
Try it in 43a78e8212c503cbaa95f3b4411462f5d2bd65b2

**Comment by DanielAdolfsson** [comment]
This works well, very nice!
