### ISSUE TITLE
Count number of connected outputs

### ISSUE THREAD

**Issue by dignifiedquire** [zakarumych/egui-snarl#32]
Hey thanks for the cool library! I am trying to count the number of currently connected outputs on a single node, could only come up with this so far

```rust
let num_connections = snarl.wires().filter(|(output, input)| {
    output.node == pin.id.node
}).count();
```
but this is quite expensive as I have to iterate over all wires. Is there a way to do this I am not seeing?

**Comment by dignifiedquire** [comment]
actually it isn't, as that only gives me that info on per output basis

**Comment by zakarumych** [comment]
Searching through all wires is intended way to do it right now.

I can add dedicated methods, but they will do it same way.
However they might be optimized someday.
