### ISSUE TITLE
Zoom is not applied to egui::ComboBox

### ISSUE THREAD

**Issue by dignifiedquire** [zakarumych/egui-snarl#36]
When using the `ComboBox` the zoom settings don't seem to be applied, and I am not quite sure on how to proxy the scale through properly.

**Comment by zakarumych** [comment]
This issue should be fixed in egui. There's function `popup_above_or_below_widget` that creates new `Ui` instance to place elements in the dropdown. And it doesn't inherit style of the parent ui.

**Comment by ThePagi** [comment]
I forked snarl and changed egui version to 0.29.1, can confirm this is fixed now.
