### ISSUE TITLE
Can i refactoring code?

### ISSUE THREAD

**Issue by nrot** [zakarumych/egui-snarl#4]
Can I fix the formatting according to clippy's recommendations? Like:
- [ ] [unnecessary_lazy_evaluations](https://rust-lang.github.io/rust-clippy/master/index.html#/unnecessary_lazy_evaluations)
- [ ] [toplevel_ref_arg](https://rust-lang.github.io/rust-clippy/master/index.html#/toplevel_ref_arg)
- [ ] [needless_borrow](https://rust-lang.github.io/rust-clippy/master/index.html#/needless_borrow)
- [ ] [let_unit_value](https://rust-lang.github.io/rust-clippy/master/index.html#/let_unit_value)
- [ ] [collapsible_if](https://rust-lang.github.io/rust-clippy/master/index.html#/collapsible_if)

Can i refactroring code to split ```Snarl<T>::show(...)``` to separated parts?

**Comment by zakarumych** [comment]
Fixing lints and typos is always welcome.
I'm not against refactoring for stylistic and ergonomic purposes either, but if you want to shift API considerably make a discussion first.
You also may refactor internals if you know you can make it better.
