### ISSUE TITLE
Can I use pinch-in, pinch-out?

### ISSUE THREAD

**Issue by oligamiq** [zakarumych/egui-snarl#42]
I usual use pinch-in, pinch-out.

**Comment by dimtpap** [comment]
Here is a hacky way to do it
```rust
// Place this before calling snarl.show
ui.input_mut(|i| i.raw_scroll_delta.y = i.zoom_delta() - 1.);
```

I wish egui-snarl zoomed based on zoom delta instead of scroll delta since I have scroll areas inside my node bodies and scrolling them makes the graph change scale.

**Comment by oligamiq** [comment]
Do you mean adding a setting that allows?

Since it would be a major change, it is unlikely that the default behavior would be changed...

**Comment by dimtpap** [comment]
Even better would be being able to set the scale programmatically then

**Comment by zakarumych** [comment]
Since 0.6 egui-snarl uses `Input::zoom_delta()` for zooming.
