### ISSUE TITLE
[Suggestion] Add vertical node layout

### ISSUE THREAD

**Issue by juh9870** [zakarumych/egui-snarl#43]
Would be great to have an option to render a node with a vertical layout, akin to blender:
![image](https://github.com/user-attachments/assets/11e91523-31f9-4795-9e83-5b90aba11469)

Output nodes on the top right, then the body, and lastly the inputs on the bottom-left.

With the current system, the nodes tend to get very wide, especially when custom body is involved, and as a result a lot of empty space is generated.

As an example, here is a simple math workflow. Notice how the nodes are basically twice as wide as they need to be at the cost of saving one row of vertical space.
![image](https://github.com/user-attachments/assets/4a124b3e-dc5b-4bc0-b712-5e3a37950713)

And it gets worse if I add a body:
![image](https://github.com/user-attachments/assets/2e2a64f5-adce-4cf1-82c1-72d280f07390)
1. Inputs
2. Body
3. Outputs

---

Not sure if the option would be better fit on per-node or per-graph basis, but I guess making it per-node would give more control to the application authors

**Comment by zakarumych** [comment]
That's excellent suggestion!
You may implemented if you want.
Or I will do it later.

**Comment by zakarumych** [comment]
Understandable. Then I will implement it. Shouldn't be too hard.
